import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/userContext";
import ResponsiveNav from "./components/Navbar";
import { Button } from "@/components/ui/button";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-screen`}
      >
      <ResponsiveNav
        logo={<span className="text-xl font-bold">CNit Academy</span>}
        rightElements={
          <div className="flex items-center space-x-2">
            <Button variant="outline" size="sm">
              Log in
            </Button>
            <Button size="sm">Sign up</Button>
          </div>
        }
      />
          <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
