import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/userContext";
import ResponsiveNav from "./components/Navbar";
import { Button, buttonVariants } from "@/components/ui/button";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-screen`}
      >
      <UserProvider>
      <ResponsiveNav/>
          {children}
      </UserProvider>
      </body>
    </html>
  );
}
